[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisord.log

[program:rsyslog]
command=/usr/sbin/rsyslogd -n
autostart=true
autorestart=true
priority=10

[program:lighttpd]
command=/usr/sbin/lighttpd -D -f /etc/lighttpd/lighttpd.conf
autostart=true
autorestart=true
priority=20

[program:suricata]
command=/usr/bin/suricata -c /etc/suricata/suricata.yaml -i eth0 --init-errors-fatal
autostart=true
autorestart=true
priority=30
startsecs=5
startretries=3
